name: Fake Deploy and Issue Creation

on:
  workflow_dispatch:

jobs:
  fake-deploy-and-issue:
    runs-on: ubuntu-latest

    steps:
    - name: Fake Checkout
      uses: actions/checkout@v3

    - name: Echo Deploy
      run: echo "Simulating deploy..."

    - name: Delay for 1 minute
      run: sleep 60s

    - name: Open Issue
      uses: peter-evans/create-issue@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        title: Erro 500
        body: | 
          Este é um erro simulado gerado por um workflow de teste.
          Por favor, investigue a causa raiz do erro 500.