jobs:
  fake-deploy-and-issue:
    runs-on: ubuntu-latest
    permissions:
      issues: write # Adicione esta linha para conceder permissão de escrita de issues

    steps:
    - name: Fake Checkout
      uses: actions/checkout@v3

    - name: Echo Deploy
      run: echo "Simulating deploy..."

    - name: Delay for 1 minute
      run: sleep 60s

    - name: Open Issue
      uses: actions-ecosystem/action-create-issue@v1
      with:
        title: Erro 500
        body: | 
          Este é um erro simulado gerado por um workflow de teste.
          Por favor, investigue a causa raiz do erro 500.

