name: Deploy with Issue Creation

on:
  workflow_dispatch:

jobs:
  fake-deploy-and-issue:
    runs-on: ubuntu-latest
    permissions:
      issues: write

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Deploy
      run: echo "Simulating deploy..."

    - name: Check Application
      run: sleep 5s

    - name: Open Issue
      uses: actions-ecosystem/action-create-issue@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        title: Erro 500
        body: | 
          Este é um erro simulado gerado por um workflow de teste.
          Por favor, investigue a causa raiz do erro 500.
        assignees: lucasviniciusrodrigues
